version: '2.27'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: lvendas
      MYSQL_PASSWORD: lvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lvendas_db


