version: '2.27'
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: lvendas
      MYSQL_PASSWORD: lvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lvendas_db

jaeger:
image:   jaegertracing/all-in-one:1.59
container_name:
ports: -p 6831:6831/udp 
       -p 6832:6832/udp 
       -p 5778:5778 
       -p 16686:16686
       -p 4317:4317 
       -p 4318:4318 
       -p 14250:14250 
       -p 14268:14268 
       -p 14269:14269 
       -p 9411:9411 
